//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMora.FamilyPhotos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\input")]
        public string Directory_Input {
            get {
                return ((string)(this["Directory_Input"]));
            }
            set {
                this["Directory_Input"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\backup")]
        public string Directory_Backup {
            get {
                return ((string)(this["Directory_Backup"]));
            }
            set {
                this["Directory_Backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\output")]
        public string Directory_Output {
            get {
                return ((string)(this["Directory_Output"]));
            }
            set {
                this["Directory_Output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\QMora_Data.xlsx")]
        public string File_ExcelData {
            get {
                return ((string)(this["File_ExcelData"]));
            }
            set {
                this["File_ExcelData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Draw_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["Draw_FontColor"]));
            }
            set {
                this["Draw_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color Draw_BackGround {
            get {
                return ((global::System.Drawing.Color)(this["Draw_BackGround"]));
            }
            set {
                this["Draw_BackGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana, 8pt")]
        public global::System.Drawing.Font Draw_Font {
            get {
                return ((global::System.Drawing.Font)(this["Draw_Font"]));
            }
            set {
                this["Draw_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Draw_Box_Height_Percentage {
            get {
                return ((int)(this["Draw_Box_Height_Percentage"]));
            }
            set {
                this["Draw_Box_Height_Percentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Draw_Box_Width_Percentage {
            get {
                return ((int)(this["Draw_Box_Width_Percentage"]));
            }
            set {
                this["Draw_Box_Width_Percentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Margin_FromLeft_Percentage {
            get {
                return ((int)(this["Margin_FromLeft_Percentage"]));
            }
            set {
                this["Margin_FromLeft_Percentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Margin_FromBotton_Percentage {
            get {
                return ((int)(this["Margin_FromBotton_Percentage"]));
            }
            set {
                this["Margin_FromBotton_Percentage"] = value;
            }
        }
    }
}
